const Clients = [
	{
		id: 1,
		name: 'Jovan Stefanović',
		phone: '0691120296',
		email: 'zbni.rs@gmail.com',
		confirmed: true,
	},
	{
		id: 2,
		name: 'Adrien Stefanović',
		phone: '0605003131',
		email: 'adrienStefanović@gmail.com',
		confirmed: true,
	},
	{
		id: 3,
		name: 'Alen Stefanović',
		phone: '0601234567',
		email: 'alenstefanovic@gmail.com',
		confirmed: true,
	},
	{
		id: 4,
		name: 'Željko Sovilj',
		phone: '0646464646',
		email: 'soviljz@gmail.com',
		confirmed: true,
	},
	{
		id: 5,
		name: 'Darko Sovilj',
		phone: '0605566445',
		email: 'soxdarko@gmail.com',
		confirmed: true,
	},
	{
		id: 6,
		name: 'Petar Petrović',
		phone: '0665646456',
		email: 'petarpetrovic@gmail.com',
		confirmed: true,
	},
	{
		id: 7,
		name: 'Mirko Mirković',
		phone: '0638523574',
		email: 'mirkovic@gmail.com',
		confirmed: true,
	},
	{
		id: 8,
		name: 'Savo Savić',
		phone: '0656485214',
		email: 'ssavic@gmail.com',
		confirmed: true,
	},
	{
		id: 9,
		name: 'Jovan Stefanović',
		phone: '0691120296',
		email: 'zbni.rs@gmail.com',
		confirmed: true,
	},
	{
		id: 10,
		name: 'Adrien Stefanović',
		phone: '0605003131',
		email: 'adrienStefanović@gmail.com',
		confirmed: true,
	},
	{
		id: 11,
		name: 'Alen Stefanović',
		phone: '0601234567',
		email: 'alenstefanovic@gmail.com',
		confirmed: true,
	},
	{
		id: 12,
		name: 'Željko Sovilj',
		phone: '0646464646',
		email: 'soviljz@gmail.com',
		confirmed: true,
	},
	{
		id: 13,
		name: 'Darko Sovilj',
		phone: '0605566445',
		email: 'soxdarko@gmail.com',
		confirmed: true,
	},
	{
		id: 14,
		name: 'Petar Petrović',
		phone: '0665646456',
		email: 'petarpetrovic@gmail.com',
		confirmed: true,
	},
	{
		id: 15,
		name: 'Mirko Mirković',
		phone: '0638523574',
		email: 'mirkovic@gmail.com',
		confirmed: true,
	},
	{
		id: 16,
		name: 'Savo Savić',
		phone: '0656485214',
		email: 'ssavic@gmail.com',
		confirmed: true,
	},
	{
		id: 17,
		name: 'Jovan Stefanović',
		phone: '0691120296',
		email: 'zbni.rs@gmail.com',
		confirmed: true,
	},
	{
		id: 18,
		name: 'Adrien Stefanović',
		phone: '0605003131',
		email: 'adrienStefanović@gmail.com',
		confirmed: true,
	},
	{
		id: 19,
		name: 'Alen Stefanović',
		phone: '0601234567',
		email: 'alenstefanovic@gmail.com',
		confirmed: true,
	},
	{
		id: 20,
		name: 'Željko Sovilj',
		phone: '0646464646',
		email: 'soviljz@gmail.com',
		confirmed: true,
	},
	{
		id: 21,
		name: 'Darko Sovilj',
		phone: '0605566445',
		email: 'soxdarko@gmail.com',
		confirmed: true,
	},
	{
		id: 22,
		name: 'Petar Petrović',
		phone: '0665646456',
		email: 'petarpetrovic@gmail.com',
		confirmed: true,
	},
	{
		id: 23,
		name: 'Mirko Mirković',
		phone: '0638523574',
		email: 'mirkovic@gmail.com',
		confirmed: true,
	},
	{
		id: 24,
		name: 'Savo Savić',
		phone: '0656485214',
		email: 'ssavic@gmail.com',
		confirmed: true,
	},
	{
		id: 25,
		name: 'Jovan Stefanović',
		phone: '0691120296',
		email: 'zbni.rs@gmail.com',
		confirmed: true,
	},
	{
		id: 26,
		name: 'Adrien Stefanović',
		phone: '0605003131',
		email: 'adrienStefanović@gmail.com',
		confirmed: true,
	},
	{
		id: 27,
		name: 'Alen Stefanović',
		phone: '0601234567',
		email: 'alenstefanovic@gmail.com',
		confirmed: true,
	},
	{
		id: 28,
		name: 'Željko Sovilj',
		phone: '0646464646',
		email: 'soviljz@gmail.com',
		confirmed: true,
	},
	{
		id: 29,
		name: 'Darko Sovilj',
		phone: '0605566445',
		email: 'soxdarko@gmail.com',
		confirmed: true,
	},
	{
		id: 30,
		name: 'Petar Petrović',
		phone: '0665646456',
		email: 'petarpetrovic@gmail.com',
		confirmed: true,
	},
	{
		id: 31,
		name: 'Mirko Mirković',
		phone: '0638523574',
		email: 'mirkovic@gmail.com',
		confirmed: true,
	},
	{
		id: 32,
		name: 'Savo Savić',
		phone: '0656485214',
		email: 'ssavic@gmail.com',
		confirmed: true,
	},
];

export default Clients;
